version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: desafio-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}  # Lê do arquivo .env
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    image: ${DOCKER_REGISTRY-}desafiotargetapi
    container_name: desafio-api
    build:
      context: .
      dockerfile: desafioTarget.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Monta a string de conexão usando a variável do .env
      - ConnectionStrings__DefaultConnection=Server=database,1433;Database=DesafioTargetDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - database

volumes:
  sqlvolume: